require "fileutils"
require "open3"

require "arduino-mk/base"
require "arduino-mk/option_parser"
require "arduino-mk/project_copier"
require "arduino-mk/makefile/template"
require "arduino-mk/makefile/runner"
require "arduino-mk/null_project"
require "arduino-mk/error_improver"
